# Generated by Django 4.2.11 on 2024-09-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_player_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="user_id",
            field=models.IntegerField(null=True),
        ),
    ]
