# Generated by Django 4.2.11 on 2024-09-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_alter_player_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="storage",
            field=models.IntegerField(default=15),
        ),
    ]
