# Generated by Django 4.2.11 on 2024-09-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_alter_game_storage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="storage",
            field=models.IntegerField(default=20, null=True),
        ),
    ]
