# Generated by Django 4.2.11 on 2024-09-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_alter_game_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="user_name",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
